# Generated by Django 3.2.1 on 2021-05-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_rename_meetingminutes_meetingminute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resourcetype',
            field=models.CharField(max_length=1500),
        ),
    ]
