# Generated by Django 3.2.1 on 2021-06-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0004_alter_resource_resourcetype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meetingminute',
            table='MeetingMinute',
        ),
    ]
